read_content_from_file:
    description: >
        Read the content from the file {file_with_feature}
    expected_output: The content of the file
    agent: local_file_manager

create_tests_for_features:
    description: >
        write the tests for the module/function/features in the path {file_with_feature}.
    expected_output: The tests, and only the tests in pytest for the new feature
    agent: tester

write_content_in_file:
    description: >
        Write the content in {write_tests_in_path}
    expected_output: A file with the content written in it
    agent: local_file_manager

calculate:
    description: >
        use the tools provided to calculate the factorial of the number 10 then divide it by 10 and 
        then add 10 to the result.
    expected_output: The result of the expression
    agent: math_expert